<?php

require 'autoload.php';
require 'config.php';

use Medoo\Medoo;

use DeadComposers\API;
use DeadComposers\Database;
use DeadComposers\Wikidata\Constants\Country;
use DeadComposers\Wikidata\Constants\Occupation;

// Wikidata Query

$target_countries = [
    Country\AFGHANISTAN,
    Country\ALBANIA,
    Country\ALGERIA,
    Country\ANDORRA,
    Country\ANGOLA,
    Country\ANTIGUA_AND_BARBUDA,
    Country\ARGENTINA,
    Country\ARMENIA,
    Country\AUSTRALIA,
    Country\AUSTRIA,
    Country\AZERBAIJAN,
    Country\BAHAMAS,
    Country\BAHRAIN,
    Country\BANGLADESH,
    Country\BARBADOS,
    Country\BELARUS,
    Country\BELGIUM,
    Country\BELIZE,
    Country\BENIN,
    Country\BHUTAN,
    Country\BOLIVIA,
    Country\BOSNIA_AND_HERZEGOVINA,
    Country\BOTSWANA,
    Country\BRAZIL,
    Country\BRUNEI,
    Country\BULGARIA,
    Country\BURKINA_FASO,
    Country\BURMA_MYANMAR,
    Country\BURUNDI,
    Country\CAMBODIA,
    Country\CAMEROON,
    Country\CANADA,
    Country\CAPE_VERDE,
    Country\CENTRAL_AFRICAN_REPUBLIC,
    Country\CHAD,
    Country\CHILE,
    Country\CHINA,
    Country\COLOMBIA,
    Country\COMOROS,
    Country\COSTA_RICA,
    Country\CROATIA,
    Country\CUBA,
    Country\CYPRUS,
    Country\CZECH_REPUBLIC,
    Country\DEMOCRATIC_REPUBLIC_CONGO,
    Country\DENMARK,
    Country\DJIBOUTI,
    Country\DOMINICA,
    Country\DOMINICAN_REPUBLIC,
    Country\ECUADOR,
    Country\EGYPT,
    Country\EL_SALVADOR,
    Country\EQUATORIAL_GUINEA,
    Country\ERITREA,
    Country\ESTONIA,
    Country\ESWATINI,
    Country\ETHIOPIA,
    Country\FIJI,
    Country\FINLAND,
    Country\FRANCE,
    Country\GABON,
    Country\GAMBIA,
    Country\GEORGIA,
    Country\GERMANY,
    Country\GHANA,
    Country\GREECE,
    Country\GRENADA,
    Country\GUATEMALA,
    Country\GUINEA,
    Country\GUINEA_BISSAU,
    Country\GUYANA,
    Country\HAITI,
    Country\HONDURAS,
    Country\HUNGARY,
    Country\ICELAND,
    Country\INDIA,
    Country\INDONESIA,
    Country\IRAN,
    Country\IRAQ,
    Country\IRELAND,
    Country\ISRAEL,
    Country\ITALY,
    Country\JAMAICA,
    Country\JAPAN,
    Country\JORDAN,
    Country\KARIBATI,
    Country\KAZAKHSTAN,
    Country\KENYA,
    Country\KUWAIT,
    Country\KYRGYZSTAN,
    Country\LAOS,
    Country\LATVIA,
    Country\LEBANON,
    Country\LESOTHO,
    Country\LIBERIA,
    Country\LIBYA,
    Country\LIECHTENSTEIN,
    Country\LITHUANIA,
    Country\LUXEMBOURG,
    Country\MACEDONIA,
    Country\MADAGASCAR,
    Country\MALAWI,
    Country\MALAYSIA,
    Country\MALDIVES,
    Country\MALI,
    Country\MAURITANIA,
    Country\MAURITIUS,
    Country\MEXICO,
    Country\MOLDOVA,
    Country\MONACO,
    Country\MONGOLIA,
    Country\MONTENEGRO,
    Country\MOROCCO,
    Country\MOZAMBIQUE,
    Country\NAMIBIA,
    Country\NAURU,
    Country\NEPAL,
    Country\NETHERLANDS,
    Country\NEW_ZEALAND,
    Country\NICARAGUA,
    Country\NIGER,
    Country\NIGERIA,
    Country\NORTH_KOREA,
    Country\NORWAY,
    Country\OMAN,
    Country\PAKISTAN,
    Country\PALAU,
    Country\PANAMA,
    Country\PAPUA_NEW_GUINEA,
    Country\PARAGUAY,
    Country\PERU,
    Country\PHILIPPINES,
    Country\POLAND,
    Country\PORTUGAL,
    Country\QATAR,
    Country\REPUBLIC_COTE_D_IVOIRE,
    Country\REPUBLIC_OF_MALTA,
    Country\ROMANIA,
    Country\RUSSIA,
    Country\RWANDA,
    Country\SAINT_KITTS_AND_NEVIS,
    Country\SAINT_LUCIA,
    Country\SAINT_VINCENT_AND_THE_GRENADINES,
    Country\SAMOA,
    Country\SAN_MARINO,
    Country\SAO_TOME_AND_PRINCIPE ,
    Country\SAUDI_ARABIA,
    Country\SENEGAL,
    Country\SERBIA,
    Country\SEYCHELLES,
    Country\SIERRA_LEONE,
    Country\SINGAPORE,
    Country\SLOVAKIA,
    Country\SLOVENIA,
    Country\SOLOMON_ISLANDS,
    Country\SOMALIA,
    Country\SOUTH_AFRICA,
    Country\SOUTH_KOREA,
    Country\SOUTH_SUDAN,
    Country\SPAIN,
    Country\SRI_LANKA,
    Country\SUDAN,
    Country\SURINAME,
    Country\SWEDEN,
    Country\SWITZERLAND,
    Country\SYRIA,
    Country\TAIWAN,
    Country\TAJIKISTAN,
    Country\TANZANIA_TANGANYIKA,
    Country\THAILAND,
    Country\TOGO,
    Country\TONGA,
    Country\TRINIDAD_AND_TOBAGO,
    Country\TUNISIA,
    Country\TURKEY,
    Country\TURKMENISTAN,
    Country\TUVALU,
    Country\UGANDA,
    Country\UKRAINE,
    Country\UNITED_ARAB_EMIRATES,
    Country\UNITED_KINGDOM,
    Country\UNITED_STATES,
    Country\URUGUAY,
    Country\UZBEKISTAN,
    Country\VANUATU,
    Country\VENEZUELA,
    Country\VIETNAM,
    Country\YEMEN,
    Country\ZAMBIA,
    Country\ZIMBABWE,
];

$occupations = [
    Occupation\COMPOSER,
];

// Database Setup

$db = new Medoo([
    'charset' => 'utf8',
    'database_name' => MYSQL_DB_NAME,
    'database_type' => 'mysql',
    'password' => MYSQL_PASSWORD,
    'server' => MYSQL_SERVER,
    'username' => MYSQL_USERNAME,
]);

// API Setup & Response

$api = new API($db, UPDATE_KEY, $target_countries, $occupations);

echo $api->handle_request(
    $_SERVER['REQUEST_METHOD'],
    $_REQUEST
);
