<?php

namespace DeadComposers\Utils;

class CountryCodes {
    private $country_codes = array(
        'af' => 'afghanistan',
        'ax' => 'åland islands',
        'al' => 'albania',
        'dz' => 'algeria',
        'as' => 'american samoa',
        'ad' => 'andorra',
        'am' => 'armenia',
        'ao' => 'angola',
        'ai' => 'anguilla',
        'aq' => 'antarctica',
        'ag' => 'antigua and barbuda',
        'ar' => 'argentina',
        'au' => 'australia',
        'at' => 'austria',
        'az' => 'azerbaijan',
        'bs' => 'bahamas',
        'bh' => 'bahrain',
        'bd' => 'bangladesh',
        'bb' => 'barbados',
        'by' => 'belarus',
        'be' => 'belgium',
        'bz' => 'belize',
        'bj' => 'benin',
        'bm' => 'bermuda',
        'bt' => 'bhutan',
        'bo' => 'bolivia',
        'ba' => 'bosnia and herzegovina',
        'bw' => 'botswana',
        'bv' => 'bouvet island',
        'br' => 'brazil',
        'io' => 'british indian ocean territory',
        'bn' => 'brunei darussalam',
        'bg' => 'bulgaria',
        'bf' => 'burkina faso',
        'bi' => 'burundi',
        'kh' => 'cambodia',
        'cm' => 'cameroon',
        'ca' => 'canada',
        'cv' => 'cape verde',
        'ky' => 'cayman islands',
        'cf' => 'central african republic',
        'td' => 'chad',
        'cl' => 'chile',
        'cn' => ['china', "people's republic of china"],
        'cx' => 'christmas island',
        'cc' => 'cocos (keeling) islands',
        'co' => 'colombia',
        'km' => 'comoros',
        'cg' => 'congo',
        'cd' => 'zaire',
        'ck' => 'cook islands',
        'cr' => 'costa rica',
        'hr' => 'croatia',
        'cu' => 'cuba',
        'ci' => ['ivory coast', "republic of côte d'ivoire", "côte d'ivoire"],
        'cy' => 'cyprus',
        'cz' => 'czech republic',
        'dk' => 'denmark',
        'dj' => 'djibouti',
        'dm' => 'dominica',
        'do' => 'dominican republic',
        'ec' => 'ecuador',
        'eg' => 'egypt',
        'sv' => 'el salvador',
        'gq' => 'equatorial guinea',
        'er' => 'eritrea',
        'ee' => 'estonia',
        'et' => 'ethiopia',
        'fk' => 'falkland islands (malvinas)',
        'fo' => 'faroe islands',
        'fj' => 'fiji',
        'fi' => 'finland',
        'fr' => 'france',
        'gf' => 'french guiana',
        'pf' => 'french polynesia',
        'tf' => 'french southern territories',
        'ga' => 'gabon',
        'gm' => 'gambia',
        'ge' => 'georgia',
        'de' => 'germany',
        'gh' => 'ghana',
        'gi' => 'gibraltar',
        'gr' => 'greece',
        'gl' => 'greenland',
        'gd' => 'grenada',
        'gp' => 'guadeloupe',
        'gu' => 'guam',
        'gt' => 'guatemala',
        'gg' => 'guernsey',
        'gn' => 'guinea',
        'gw' => 'guinea-bissau',
        'gy' => 'guyana',
        'ht' => 'haiti',
        'hm' => 'heard island and mcdonald islands',
        'va' => 'vatican city state',
        'hn' => 'honduras',
        'hk' => 'hong kong',
        'hu' => 'hungary',
        'is' => 'iceland',
        'in' => 'india',
        'id' => 'indonesia',
        'ir' => ['iran, islamic republic of', 'iran'],
        'iq' => 'iraq',
        'ie' => 'ireland',
        'im' => 'isle of man',
        'il' => 'israel',
        'it' => 'italy',
        'jm' => 'jamaica',
        'jp' => 'japan',
        'je' => 'jersey',
        'jo' => 'jordan',
        'kz' => 'kazakhstan',
        'ke' => 'kenya',
        'ki' => 'kiribati',
        'kp' => ['korea, democratic people\'s republic of', 'north corea'],
        'kr' => ['korea, republic of', 'south korea'],
        'kw' => 'kuwait',
        'kg' => 'kyrgyzstan',
        'la' => 'lao people\'s democratic republic',
        'lv' => 'latvia',
        'lb' => 'lebanon',
        'ls' => 'lesotho',
        'lr' => 'liberia',
        'ly' => 'libyan arab jamahiriya',
        'li' => 'liechtenstein',
        'lt' => 'lithuania',
        'lu' => 'luxembourg',
        'mo' => 'macao',
        'mk' => ['macedonia, the former yugoslav republic of', 'macedonia'],
        'mg' => 'madagascar',
        'mw' => 'malawi',
        'my' => 'malaysia',
        'mv' => 'maldives',
        'ml' => 'mali',
        'mt' => 'malta',
        'mh' => 'marshall islands',
        'mq' => 'martinique',
        'mr' => 'mauritania',
        'mu' => 'mauritius',
        'yt' => 'mayotte',
        'mx' => 'mexico',
        'fm' => 'micronesia, federated states of',
        'md' => ['moldova, republic of', 'moldova'],
        'mc' => 'monaco',
        'mn' => 'mongolia',
        'me' => 'montenegro',
        'ms' => 'montserrat',
        'ma' => 'morocco',
        'mz' => 'mozambique',
        'mm' => 'myanmar',
        'na' => 'namibia',
        'nr' => 'nauru',
        'np' => 'nepal',
        'nl' => 'netherlands',
        'an' => 'netherlands antilles',
        'nc' => 'new caledonia',
        'nz' => 'new zealand',
        'ni' => 'nicaragua',
        'ne' => 'niger',
        'ng' => 'nigeria',
        'nu' => 'niue',
        'nf' => 'norfolk island',
        'mp' => 'northern mariana islands',
        'no' => 'norway',
        'om' => 'oman',
        'pk' => 'pakistan',
        'pw' => 'palau',
        'ps' => 'palestinian territory, occupied',
        'pa' => 'panama',
        'pg' => 'papua new guinea',
        'py' => 'paraguay',
        'pe' => 'peru',
        'ph' => 'philippines',
        'pn' => 'pitcairn',
        'pl' => 'poland',
        'pt' => 'portugal',
        'pr' => 'puerto rico',
        'qa' => 'qatar',
        're' => 'réunion',
        'ro' => 'romania',
        'ru' => ['russia', 'russian federation', 'soviet union'],
        'rw' => 'rwanda',
        'sh' => 'saint helena',
        'kn' => 'saint kitts and nevis',
        'lc' => 'saint lucia',
        'pm' => 'saint pierre and miquelon',
        'vc' => 'saint vincent and the grenadines',
        'ws' => 'samoa',
        'sm' => 'san marino',
        'st' => 'sao tome and principe',
        'sa' => 'saudi arabia',
        'sn' => 'senegal',
        'rs' => 'serbia',
        'sc' => 'seychelles',
        'sl' => 'sierra leone',
        'sg' => 'singapore',
        'sk' => 'slovakia',
        'si' => 'slovenia',
        'sb' => 'solomon islands',
        'so' => 'somalia',
        'za' => 'south africa',
        'gs' => 'south georgia and the south sandwich islands',
        'es' => 'spain',
        'lk' => 'sri lanka',
        'sd' => 'sudan',
        'sr' => 'suriname',
        'sj' => 'svalbard and jan mayen',
        'sz' => 'swaziland',
        'se' => 'sweden',
        'ch' => 'switzerland',
        'sy' => ['syrian arab republic', 'syria'],
        'tw' => ['taiwan, province of china', 'taiwan'],
        'tj' => 'tajikistan',
        'tz' => ['tanzania, united republic of', 'tanzania'],
        'th' => 'thailand',
        'tl' => 'timor-leste',
        'tg' => 'togo',
        'tk' => 'tokelau',
        'to' => 'tonga',
        'tt' => 'trinidad and tobago',
        'tn' => 'tunisia',
        'tr' => 'turkey',
        'tm' => 'turkmenistan',
        'tc' => 'turks and caicos islands',
        'tv' => 'tuvalu',
        'ug' => 'uganda',
        'ua' => 'ukraine',
        'ae' => 'united arab emirates',
        'gb' => 'united kingdom',
        'us' => ['united states', 'united states of america'],
        'um' => 'united states minor outlying islands',
        'uy' => 'uruguay',
        'uz' => 'uzbekistan',
        'vu' => 'vanuatu',
        've' => 'venezuela',
        'vn' => ['viet nam', 'vietnam'],
        'vg' => 'virgin islands, british',
        'vi' => 'virgin islands, u.s.',
        'wf' => 'wallis and futuna',
        'eh' => 'western sahara',
        'ye' => 'yemen',
        'zm' => 'zambia',
        'zw' => 'zimbabwe',
    );

    function get_country($country_code) {
        if (!array_key_exists($country_code, $this->country_codes)) {
            return false;
        }

        $countries = $this->country_codes[$country_code];

        if (is_array($countries)) {
            return $countries[0];
        }

        return $countries;
    }

    function get_country_code($country_name) {
        $search_key = strtolower($country_name);
        $found = false;

        foreach ($this->country_codes as $county_code => $countries) {
            if (is_array($countries)) {
                foreach ($countries as $country) {
                    if ($search_key === $country) {
                        $found = $county_code;
                    }
                }
            } else if ($search_key === $countries) {
                $found = $county_code;
            }
        }

        return $found;
    }
}
